### ISSUE TITLE
Filter by infrastructure type

### ISSUE THREAD

**Issue by pyrog** [openinframap/web#12]
Add a toggling a list to hide/show Telecom, Power, Oil, Water… would be useful too 😀

See [example](https://docs.mapbox.com/mapbox-gl-js/example/filter-markers/).

**Comment by fconrotte** [comment]
Yes i agree ! Would be really useful :)

**Comment by russss** [comment]
Done!

**Comment by pyrog** [comment]
Thanks a lot 😀
