### ISSUE TITLE
Add reference numbers for substation street cabinets 

### ISSUE THREAD

**Issue by Adamant36** [openinframap/web#15]
Hi there. It would be really awesome if you could add ref numbers for substation street cabinets. I see you already have them for power poles. Which has really useful with helping me see which ones still have ref numbers. So it would be great if they displayed for substation street cabinets also. 

Thanks.

**Comment by sawik-PL** [comment]
That would be great to display ref= value for power=substation nodes/ways
Ref could be shown after clicking on substation, too.

**Comment by russss** [comment]
This is now done.
