### ISSUE TITLE
a URL scheme for linking to specific layer settings

### ISSUE THREAD

**Issue by danstowell** [openinframap/web#16]
Hi - I'd really like to be able to share OpenInfraMap links with people, which link directly to a view showing (e.g.) the power and solar layers. Could I put in a request for that please?

OpenStreetMap uses a basic scheme in the URL with `&layers=TN` where `T` and `N` represent two layers to be activated. Whether or not the scheme is similar, that's the functionality I have in mind...

**Comment by russss** [comment]
I've now fixed this using some code I already had.
