### ISSUE TITLE
Mixed voltage lines are offset at zoom levels where other value is no longer shown

### ISSUE THREAD

**Issue by robert-ancell** [openinframap/web#49]
If you have a power_line with a mixed voltage (e.g. 33000;11000) these are shown as two parallel lines (one for each voltage). However, if you zoom out to a level where one voltage is no longer shown (e.g. the 11000 is no longer visible) the other voltage is still shown with an offset. I would expect the renderer to treat this as a single voltage line at this level (33000).

e.g.
https://openinframap.org/#9.99/-37.6585/175.517

![osm-power-line-offset1](https://user-images.githubusercontent.com/126560/114100754-e084da80-9918-11eb-85fd-26c59d3bc1e7.png)
![osm-power-line-offset2](https://user-images.githubusercontent.com/126560/114100759-e37fcb00-9918-11eb-93a5-0264777c4c6d.png)

**Comment by russss** [comment]
Thanks! This has been slightly annoying me for a while now and you reminded me about it.

It should be mostly fixed - there's still a small zoom range where the offset will ease in before the other voltages are shown, but the alternative here is for the other voltages to appear over the top of the higher voltage, which looks worse.
