### ISSUE TITLE
Bad link to OSM node

### ISSUE THREAD

**Issue by pyrog** [openinframap/web#6]
The `OSM ID` is linked to a [way](https://openstreetmap.org/way/5966013822), but should linked to a [node](https://openstreetmap.org/node/5966013822).

OSM ID | 5966013822
-- | --
Is Node 
Substation  | minor_distribution
Voltage | 20 kV

See https://openinframap.org/#17.9/46.581639/5.745501

**Comment by russss** [comment]
I've substantially improved this if not fixed it now.

**Comment by pyrog** [comment]
Fine for substations: Thank you 😊
[node/2994720942
<img width="478" alt="Capture d’écran 2019-03-19 à 17 53 01" src="https://user-images.githubusercontent.com/2158081/54625831-4ff8aa80-4a70-11e9-8297-a49618709716.png">](https://openinframap.org/#17.9/46.529605/5.549235)

But not yet for poles: Could you reopen this issue?
[node/6316737398
<img width="464" alt="Capture d’écran 2019-03-19 à 17 53 15" src="https://user-images.githubusercontent.com/2158081/54625830-4ff8aa80-4a70-11e9-9e26-ecfbb69ae735.png">](https://openinframap.org/#17.9/46.529605/5.549235)

PS: the fix is in [infopopup.js#L37](https://github.com/openinframap/web/blob/master/src/infopopup.js#L37). It seem that some nodes don't have yet the `is_node` key.

**Comment by pathmapper** [comment]
Type `tower` is also linked to way.

![Auswahl_619](https://user-images.githubusercontent.com/20856381/62274988-39f8ee80-b441-11e9-8977-4ff16ce39220.png)

**Comment by boothym** [comment]
This is also an issue with telecoms_mast and power_wind_turbine nodes

**Comment by pyrog** [comment]
`power_tower` and `power_pole` issue seem already there ?

Examples:
* [power_pole](https://openinframap.org/#17.9/46.529605/5.549235)
* [power_tower](https://openinframap.org/#16.22/46.860884/5.733173)
* [telecoms_mast](https://openinframap.org/#17.9/46.580976/5.746578)
* [power_wind_turbine](https://openinframap.org/#14.9/46.8499/5.74444)

**Comment by russss** [comment]
I hope these all now work, some may be subject to caching.

**Comment by boothym** [comment]
Yep, nodes now work for me, thanks! 👍

**Comment by pyrog** [comment]
All examples work fine. Thank you 😄
